### ISSUE TITLE
Update Psalm action tag

### ISSUE THREAD

**Issue by eroullit** [psalm/psalm-github-security-scan#10]
The latest Actions run to publish updated docker image are running [successfully](https://github.com/psalm/psalm-github-security-scan/actions/runs/4269176706) and the resulting image can be used to scan a PHP project.

The latest tag available for this action is [1.2.1](https://github.com/psalm/psalm-github-security-scan/releases/tag/1.2.1) from Nov 2020.

Now that the action is back in shape and freshly updated can it get a new tag?

**Comment by weirdan** [comment]
[1.3.0](https://github.com/psalm/psalm-github-security-scan/releases/tag/1.3.0) has been tagged.

**Comment by weirdan** [comment]
But since workflows reference the container directly, the tag on this repo probably doesn't matter.

**Comment by eroullit** [comment]
Yes, that's correct.
Specifying which docker image version must be used in the action would make it better defined and repeatable.
I am going to try out the latest docker image tag then.

**Comment by eroullit** [comment]
Hi @weirdan ! 👋 

I have prepared PR #11 to reference the latest tag automatically on the `action.yml` file automatically. 🙌
