### ISSUE TITLE
Permission change needed to restore image publication workflow

### ISSUE THREAD

**Issue by eroullit** [psalm/psalm-github-security-scan#9]
The docker image publication workflow [watch.yml](https://github.com/psalm/psalm-github-security-scan/blob/master/.github/workflows/watch.yml) now uses `GITHUB_TOKEN` to push updated images to Psalm's GitHub Container Registry.

Though the permissions are explicitly defined in workflow file, the [Workflow Permissions](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#setting-the-permissions-of-the-github_token-for-your-repository) must be set to `Read and write permissions` either in this repository or in the Psalm's organisation settings to grant `packages: write` access to the `GITHUB_TOKEN`.

Once done, the next workflow trigger should successfully push the image on the container registry thus finalising the work started in #8.

**Comment by weirdan** [comment]
> the [Workflow Permissions](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#setting-the-permissions-of-the-github_token-for-your-repository) must be set to Read and write permissions either in this repository

It was. However, the package repo (organization-wide) did not allow the source repository to upload docker images. I had to fix it in the package repo settings:

![image](https://user-images.githubusercontent.com/57403/221139162-7d10636b-8db2-4ce6-b195-b2ac4738e2d0.png)

After it was done, the workflow succeeded: https://github.com/psalm/psalm-github-security-scan/actions/runs/4260734607

**Comment by eroullit** [comment]
Great news ! 🙌
